"""Add game to abs

Revision ID: 00d7641f68ac
Revises: b1a1b7eb4d45
Create Date: 2024-03-21 11:34:29.517042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d7641f68ac'
down_revision = 'b1a1b7eb4d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
