"""Add cascade delete to abs

Revision ID: 12179ea47d05
Revises: acefd8e0223a
Create Date: 2024-03-18 15:52:53.860095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12179ea47d05'
down_revision = 'acefd8e0223a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
