"""add pitcher outings

Revision ID: 266d674be994
Revises: 9e1ac65ffccb
Create Date: 2024-04-11 19:02:46.354728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266d674be994'
down_revision = '9e1ac65ffccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
