"""Create Database

Revision ID: 3bd4a40b12e8
Revises: 
Create Date: 2024-02-08 03:19:03.409708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd4a40b12e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor', sa.String(), nullable=True),
    sa.Column('home', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Integer(), nullable=True),
    sa.Column('precipitation', sa.String(), nullable=True),
    sa.Column('cloud_or_sun', sa.String(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hitter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitcher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('at_bat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=True),
    sa.Column('pitches', sa.String(), nullable=True),
    sa.Column('balls', sa.String(), nullable=True),
    sa.Column('strikes', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('strength', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('rbi', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('sb', sa.Integer(), nullable=True),
    sa.Column('sb_att', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('hitter_id', sa.Integer(), nullable=True),
    sa.Column('pitcher_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_at_bat_game_id_game')),
    sa.ForeignKeyConstraint(['hitter_id'], ['hitter.id'], name=op.f('fk_at_bat_hitter_id_hitter')),
    sa.ForeignKeyConstraint(['pitcher_id'], ['pitcher.id'], name=op.f('fk_at_bat_pitcher_id_pitcher')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('at_bat')
    op.drop_table('pitcher')
    op.drop_table('hitter')
    op.drop_table('game')
    # ### end Alembic commands ###
