"""Update model errors

Revision ID: 5c92ccfb6ad1
Revises: 00d7641f68ac
Create Date: 2024-03-21 11:47:27.657623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c92ccfb6ad1'
down_revision = '00d7641f68ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
