"""Add relationships between players and games

Revision ID: 6d7ae3cfbd5a
Revises: 12179ea47d05
Create Date: 2024-03-21 11:26:01.951455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7ae3cfbd5a'
down_revision = '12179ea47d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
