"""Update model errors x3

Revision ID: 80c4a46f966a
Revises: 935134d5b316
Create Date: 2024-03-21 12:11:52.130036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c4a46f966a'
down_revision = '935134d5b316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
