"""Update model errors x2

Revision ID: 935134d5b316
Revises: 5c92ccfb6ad1
Create Date: 2024-03-21 11:48:32.133302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935134d5b316'
down_revision = '5c92ccfb6ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
