"""Add outs to atbats

Revision ID: 9c85f3278a03
Revises: e7e4c0f19d31
Create Date: 2024-03-25 11:01:11.120129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c85f3278a03'
down_revision = 'e7e4c0f19d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('at_bat', sa.Column('outs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('at_bat', 'outs')
    # ### end Alembic commands ###
