"""Add arm and bat side

Revision ID: af0d6c9a8243
Revises: 35da05b12b55
Create Date: 2024-02-09 20:01:49.336037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0d6c9a8243'
down_revision = '35da05b12b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hitter', sa.Column('bat', sa.String(), nullable=True))
    op.add_column('pitcher', sa.Column('arm', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitcher', 'arm')
    op.drop_column('hitter', 'bat')
    # ### end Alembic commands ###
