"""Add join table

Revision ID: b1a1b7eb4d45
Revises: 6d7ae3cfbd5a
Create Date: 2024-03-21 11:28:25.038955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a1b7eb4d45'
down_revision = '6d7ae3cfbd5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
