"""Try association proxy

Revision ID: e47e02bec5e3
Revises: e871f7ccccd4
Create Date: 2024-03-21 12:48:44.783283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47e02bec5e3'
down_revision = 'e871f7ccccd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
