"""Add pitcher values to games

Revision ID: e7e4c0f19d31
Revises: e47e02bec5e3
Create Date: 2024-03-24 22:34:56.257209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e4c0f19d31'
down_revision = 'e47e02bec5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('home_pitcher_result', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('away_pitcher_result', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'away_pitcher_result')
    op.drop_column('game', 'home_pitcher_result')
    # ### end Alembic commands ###
