"""Update model errors x4

Revision ID: e871f7ccccd4
Revises: 80c4a46f966a
Create Date: 2024-03-21 12:36:40.994651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e871f7ccccd4'
down_revision = '80c4a46f966a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
